# Generated by Django 5.1.1 on 2024-10-13 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conversa', models.CharField(max_length=200, unique=True)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('input_gpt', models.CharField(blank=True, max_length=200, null=True)),
                ('id_conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacao_conversa', to='myapp.conversa')),
            ],
        ),
    ]
