# Generated by Django 5.0.1 on 2024-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="service",
            field=models.TextField(blank=True, null=True),
        ),
    ]
