# Generated by Django 5.0.1 on 2024-10-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_interaction_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agendamento",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="date",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="professional",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="service",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="step",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="time",
        ),
    ]
